simulator : 
  folder : "one_lane"
  time_step : 1 
  finish_time : 500
  seed : 22
  quick_mode : 0
  evaluation :
    time_step : 10
    queue_length : "on"
    delay_time : "on"
    calc_time : "off"
  save : 
    results: "on"
    time_series : "on"
    

mpc :
  dt : 2
  N_p : 4
  N_c : 2
  D_o : 100

scoot : 
  split_change_width : 4
  initial_cycle_time : 60
  min_split_time : 10
  emergency_threshold : 1.3
  alpha : 0.8
  beta : 0.2
  yellow_time : 1
  red_time : 1


  