parameters: 
  roads:
    - id: 1
      speed: 60
      inflows: 700
    - id: 2
      speed: 60
    - id: 3
      speed: 60
    - id: 4
      speed: 60
      inflows: 700
    - id: 5
      speed: 60
      inflows: 700
    - id: 6
      speed: 60
    - id: 7
      speed: 60
    - id: 8
      speed: 60
      inflows: 700

  intersections:
    - id: 1
      roads:
        - id: 1
          rel_flows:
            - id: 1
              value: 1
            - id: 2
              value: 3
            - id: 3
              value: 1
          template_id: 1
        - id: 2
          rel_flows:
            - id: 1
              value: 1
            - id: 2
              value: 3
            - id: 3
              value: 1
          template_id: 1
        - id: 3
          rel_flows:
            - id: 1
              value: 1
            - id: 2
              value: 3
            - id: 3
              value: 1
          template_id: 1
        - id: 4
          rel_flows:
            - id: 1
              value: 1
            - id: 2
              value: 3
            - id: 3
              value: 1
          template_id: 1